### ISSUE TITLE
Voice activity v1.8.32 debug error [Bug]

### ISSUE THREAD

**Issue by bubblycatbread** [Neodymium7/BetterDiscordStuff#71] opened 2024-10-21 19:03 UTC
**Addon Name and Version**
Voice activity v1.8.32

**Discord Version**
Stable

**Describe the bug**
Getting this error debug

`[2024-10-21 18:54:01.867][CONSOLE:ERROR] [BetterDiscord] [Patcher] Could not fire after callback of render for VoiceActivity Cannot read properties of undefined (reading 'type')
TypeError: Cannot read properties of undefined (reading 'type')
    at Object.eval [as callback] (betterdiscord://plugins/VoiceActivity.plugin.js:1060:18)
    at betterdiscord/renderer.js:5:22972
    at aA (https://discord.com/assets/web.16ae88492e57a3ffedb4.js:12:992550)
    at sc (https://discord.com/assets/web.16ae88492e57a3ffedb4.js:12:1002869)
    at l (https://discord.com/assets/web.16ae88492e57a3ffedb4.js:12:1049881)
    at ok (https://discord.com/assets/web.16ae88492e57a3ffedb4.js:12:1030781)
    at https://discord.com/assets/web.16ae88492e57a3ffedb4.js:12:1030647
    at oG (https://discord.com/assets/web.16ae88492e57a3ffedb4.js:12:1030655)
    at oO (https://discord.com/assets/web.16ae88492e57a3ffedb4.js:12:1025692)
    at N (https://discord.com/assets/web.16ae88492e57a3ffedb4.js:12:1224434)
    at y (https://discord.com/assets/web.16ae88492e57a3ffedb4.js:12:1224964)
    at https://discord.com/assets/web.16ae88492e57a3ffedb4.js:1:706179
    at D (https://discord.com/assets/web.16ae88492e57a3ffedb4.js:1:705944)
    at MessagePort.b (https://discord.com/assets/web.16ae88492e57a3ffedb4.js:1:706003)
`

**To Reproduce**
I'm not sure what the trigger is. It might be when I look at a server with people on voice call. 

**Screenshots**
![image](https://github.com/user-attachments/assets/7edc0429-70ad-46b8-9fce-93ef68e6fa34)

**Additional context**
Add any other context about the problem here. For example, any other plugins you have enabled that could cause compatibility issues.

**Comment by Neodymium7** [comment] 2024-12-14 05:44
I still haven’t been able to reproduce this error, and the plugin’s been updated a few times since this was posted. That error message alone doesn’t seem like anything super problematic, so I’m going to go ahead and close this. If you run into any problems feel free to make another issue!

**Closed as not planned by Neodymium7** 2024-12-14 05:44 UTC
Labels: bug
