### ISSUE TITLE
[Bug] - Voiceactivity makes me crash

### ISSUE THREAD

**Issue by Soulivan71** [Neodymium7/BetterDiscordStuff#24] opened 2022-10-27 01:15 UTC
**Addon Name and Version**
VoiceActivity v 1.2.5

**Discord Version**
Ptb 154608 (d4b0979) Host 1.0.1019 Windows 10 64-Bit (10.0.19044)

**Describe the bug**
Enable voiceactivity and when I clic on a nickname I crash (well this is awkward)

**To Reproduce**
Juste enabled it and I have the following screens :

**Screenshots**
![image](https://user-images.githubusercontent.com/36502190/198167936-1bb5bf9c-461a-42e0-9e82-8ed6aff05a76.png)
![image](https://user-images.githubusercontent.com/36502190/198168091-f4f48751-8a29-4818-a0f8-e59ab43fbcf5.png)
![image](https://user-images.githubusercontent.com/36502190/198168132-f72f46b8-e818-48ed-ad00-0df4b9f8c01f.png)

**Additional context**
U can find all my tries here -> https://canary.discord.com/channels/86004744966914048/1034955093621084190

**Comment by Soulivan71** [comment] 2022-10-27 01:21
So I gave u all my errors come back to me if u need more info
@Neodymium7

**Comment by Soulivan71** [comment] 2022-10-27 01:29
![image](https://user-images.githubusercontent.com/36502190/198169765-9ed1066a-db6c-48c3-88f3-a033b96712f3.png)

**Comment by Neodymium7** [comment] 2022-10-27 01:32
Does it happen with every single user or just one specific one?

**Comment by Soulivan71** [comment] 2022-10-27 01:52
With everyone (chat nickname) (in vc) (server memberlist)

**Comment by Neodymium7** [comment] 2022-10-27 01:57
So only people with a nickname that are in a voice chat? Or are you saying whenever you open a popout?

Are the users all in a voice chat or does it crash even if they're not?

**Comment by Soulivan71** [comment] 2022-10-27 01:59
When I open a popout yes
And I just say that happened everywhere that I can found something to click like => 
> With everyone (chat nickname) (in vc) (server memberlist) etc etc

**Comment by Neodymium7** [comment] 2022-10-27 02:04
Got it. I’m still unable to reproduce it, but I’ll keep looking. In the meantime if you find any more info feel free to let me know.

**Comment by RDP8** [comment] 2022-10-27 21:08
![image](https://user-images.githubusercontent.com/87581810/198398443-a6cdbb30-e4af-4c65-a5f1-fdf1bea179b8.png)
I simply just click on anyone in a server, and this happens and crashes my discord saying this is awkward.

**Comment by Neodymium7** [comment] 2022-10-27 21:10
> ![image](https://user-images.githubusercontent.com/87581810/198398443-a6cdbb30-e4af-4c65-a5f1-fdf1bea179b8.png)
> 
> I simply just click on anyone in a server, and this happens and crashes my discord saying this is awkward. 

Which version of Discord are you on?

**Comment by RDP8** [comment] 2022-10-27 21:13
> > ![image](https://user-images.githubusercontent.com/87581810/198398443-a6cdbb30-e4af-4c65-a5f1-fdf1bea179b8.png)
> > I simply just click on anyone in a server, and this happens and crashes my discord saying this is awkward.
> 
> Which version of Discord are you on?

![image](https://user-images.githubusercontent.com/87581810/198399327-bb798354-a8cb-421f-8cbb-c040f4f416c5.png)

**Comment by Neodymium7** [comment] 2022-10-27 21:19
Does it happen in every single server as well as DMs or only in a specific server?

**Comment by RDP8** [comment] 2022-10-27 21:27
> Does it happen in every single server and DM, or only in a specific server?

If I click someone in a dm, it doesn't crash discord, but if I go and look in any server and then 
click anyone anywhere, it crashes.

**Comment by Neodymium7** [comment] 2022-10-27 21:35
Can you disable the plugin and send a screenshot of what your user popouts look like?

**Comment by RDP8** [comment] 2022-10-27 21:42
> Can you disable the plugin and send a screenshot of what your user popouts look like?

Sure, 
![image](https://user-images.githubusercontent.com/87581810/198403795-73a8ab57-fac7-485b-82d2-cec8a468c646.png)
This is what you mean, right?

**Comment by Neodymium7** [comment] 2022-10-27 21:46
Yep, thanks

**Comment by Neodymium7** [comment] 2022-10-27 21:53
[VoiceActivity.plugin.txt](https://github.com/Neodymium7/BetterDiscordStuff/files/9883332/VoiceActivity.plugin.txt)
Try using this version and let me know if it still crashes (Replace the .txt with .js)

**Comment by RDP8** [comment] 2022-10-27 21:59
> [VoiceActivity.plugin.txt](https://github.com/Neodymium7/BetterDiscordStuff/files/9883332/VoiceActivity.plugin.txt) Try using this version and let me know if it still crashes (Replace the .txt with .js)

Yep, that fixed it, thanks.

**Comment by Neodymium7** [comment] 2022-10-27 22:01
Oh cool, let me know if you have any more issues. I’ll push out the update officially later today.

**Comment by TheGreatTaz** [comment] 2022-10-27 22:12
oh cool, a fix.
I was just coming here with the same problem

**Comment by Neodymium7** [comment] 2022-10-28 02:14
Just pushed the fix. Let me know if you experience any other issues!

**Closed as completed by Neodymium7** 2022-10-28 02:14 UTC
Labels: bug

**Comment by Soulivan71** [comment] 2022-10-28 06:53
Fix for me thx
