### ISSUE TITLE
[Bug] VoiceActivity dont shows hidden channels

### ISSUE THREAD

**Issue by ledgerkeeper** [Neodymium7/BetterDiscordStuff#31] opened 2023-01-12 00:35 UTC
**Addon Name and Version**
VoiceActivity 1.6.1

**Discord Version**
Discord PTB

**Describe the bug**
I cant see VoiceActivity for users who in hidden channel rn 
Public channels works well

**Additional context**
I using this new, working version, return-ShowHiddenChannels:
https://github.com/JustOptimize/return-ShowHiddenChannels

**Comment by Neodymium7** [comment] 2023-01-12 00:39
This is a duplicate of #21. See the comments on that issue for more information.

**Closed as not planned by Neodymium7** 2023-01-12 00:39 UTC
Labels: bug
