### ISSUE TITLE
[Bug] VoiceActivity Icon in Member List showing twice

### ISSUE THREAD

**Issue by XCraftTM** [Neodymium7/BetterDiscordStuff#20] opened 2022-09-14 11:53 UTC
**Addon Name and Version**
VoiceActivity v1.4.1

**Discord Version**
Discord Stable with Better Discord latest.

**Describe the bug**
It shows the Voice Activity Icon twice in the Member List on the Right of a Server(for me and for everyone else that is in a talk)

**To Reproduce**
Plugin enabled, join a voice channel.

**Screenshots**
![image](https://user-images.githubusercontent.com/72396660/190146088-a9ab1971-1d6e-4e7c-81d9-81635f56de9b.png)

**Additional context**
I don't really know what plugins could cause problems with the plugin so here is my entire Plugin list that was created by BetterDiscord:
https://pastebin.com/i2fdVMaF

_If this is an duplicate then i am sorry._

**Comment by XCraftTM** [comment] 2022-09-14 11:54
Quickly adding that both of the icons are working like they should(Clickable, and Hoverable)

**Comment by Neodymium7** [comment] 2022-09-14 17:55
Thanks for letting me know! I’ll take a look at it once I get back to my PC. 

Did you happen to update the plugin before the duplicate icon appeared? It’s possible updating could cause issues like that, and if so, you could fix it by restarting/reloading Discord. If restarting fixes it, let me know and I’ll try to see if I can do anything about any weird issues after updating.

**Comment by XCraftTM** [comment] 2022-09-14 18:06
No it was a Bug since i had the Plugin(maybe already 1 Year).
Also Yeah restarting fixes the issue.

**Comment by Neodymium7** [comment] 2022-09-14 18:12
So when exactly do the duplicate icons appear? When you update, when you start discord, when you start the plugin, etc.

**Comment by XCraftTM** [comment] 2022-09-14 18:16
Not when Updating(Tested with 1.4.0 -> 1.4.1). Not when Starting Discord. Not when starting the Plugin.

**Comment by XCraftTM** [comment] 2022-09-14 18:17
I have troubles recreating the Problem

**Comment by Neodymium7** [comment] 2022-09-14 19:05
Alright, thanks for the info. I’ll see if I can find what’s causing it.

**Comment by NeverEndingCycle** [comment] 2022-11-01 06:28
Also having this issue.

**Comment by Soulivan71** [comment] 2022-12-19 00:58
Same issue with 1.6.0

**Comment by Neodymium7** [comment] 2022-12-19 00:59
Does restarting Discord or reloading with Ctrl+R fix it?

**Comment by Soulivan71** [comment] 2022-12-19 01:01
Hmm yes mb

**Comment by Neodymium7** [comment] 2022-12-19 01:07
Yeah, I’ve tried to reproduce it, but the only time it’s happened for me is after updating, and restarting was able to fix it. I’ve also tried unsuccessfully to prevent it from happening, but I still can’t figure out what exactly is causing it. There’s a chance I might not be able to do anything about it all. I’m going to close this issue for now, since it seems to be a temporary problem that doesn’t occur very often and can be fixed easily by a reload. I’ll still keep a lookout in case I can find a solution.

**Comment by Soulivan71** [comment] 2022-12-19 01:08
Is this : "Added corresponding settings for new features, and new setting for toggling profile section" => the experiments ?? : 
![Image]
Cause I don't understand this new thing in changelog can u explain me ? @Neodymium7

**Closed as completed by Neodymium7** 2022-12-19 01:07 UTC
Labels: bug

**Comment by Neodymium7** [comment] 2022-12-19 01:10
There’s a better description on the actual setting. There should be settings to toggle every feature of the plugin now, including one to toggle the profile section that appears in user popouts and the DM profile experiment.

**Comment by Soulivan71** [comment] 2022-12-19 01:11
Ok thx
